### ISSUE TITLE
schematics?

### ISSUE THREAD

**Issue by rkhoury** [ildus/owly#1]
Hey Ildus,

I was recently given a STM32F407 and a WM8731S to make a programmable guitar effects setup, but I'm more of a programmer than I am a electrical engineer.  I was very happy to find this repo which will help me get set up on the software side, but I was wondering if you had any schematics for your guitar effects setup so that I can get set up without ruining anything? I this something that could be attached to this project?

Many thanks!

**Comment by ildus** [comment]
Hey, I would suggest for you to take look at https://github.com/pingdynasty/OwlWare and https://github.com/JonasNorling/guitarboard . They are fully working projects on same hardware (STM32 and WM8731). I was inspired by them.
My project was never finished and I'm planning to continue this year, and it could take a long time until it can be used somewhere.

**Comment by rkhoury** [comment]
Many thanks for the links!

Best of luck with your project 🙂

**Comment by ildus** [comment]
Thank you!
